### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by rsrini7** [brooth/jeta-samples#1]
I am facing below exception while trying to execute any of the samples.

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException: Failed to load class org.brooth.jeta.samples.MetasitoryContainer
    at org.brooth.jeta.metasitory.MapMetasitory.loadContainer(MapMetasitory.java:59)
    at org.brooth.jeta.metasitory.MapMetasitory.<init>(MapMetasitory.java:49)
    at org.brooth.jeta.samples.MetaHelper.<init>(MetaHelper.java:68)
    at org.brooth.jeta.samples.MetaHelper.getInstance(MetaHelper.java:63)
    at org.brooth.jeta.samples.MetaHelper.getMultiton(MetaHelper.java:134)
    at org.brooth.jeta.samples.singleton.MultitonSample.<clinit>(MultitonSample.java:30)
Caused by: java.lang.ClassNotFoundException: org.brooth.jeta.samples.MetasitoryContainer
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.brooth.jeta.metasitory.MapMetasitory.loadContainer(MapMetasitory.java:56)
    ... 5 more

**Comment by brooth** [comment]
You need to generate all the meta code before execute the samples. Please, run `build` command first.

**Comment by rsrini7** [comment]
Thanks. The problem in eclipse is that i have to explicitly specify the Generated Source directory as "build/generated/source/apt/main" from default ".apt_generated"
